# Generated by Django 5.2.16 on 2026-07-31 10:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('min_reviews', models.PositiveIntegerField(default=0, help_text='Published reviews required to earn this badge automatically')),
            ],
            options={
                'ordering': ['min_reviews'],
            },
        ),
        migrations.CreateModel(
            name='ReviewerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('reputation', models.PositiveIntegerField(default=0)),
                ('is_trusted', models.BooleanField(default=False, help_text='Trusted Reviewer status granted by admins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reputation'],
            },
        ),
        migrations.CreateModel(
            name='ReviewerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='accounts.badge')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='accounts.reviewerprofile')),
            ],
            options={
                'unique_together': {('profile', 'badge')},
            },
        ),
    ]
