# Generated by Django 5.2.16 on 2026-07-31 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationtoken_owneraccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerprofile',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Blocked reviewers cannot submit new reviews'),
        ),
        migrations.AddField(
            model_name='reviewerprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
