# Generated by Django 5.2.17 on 2026-09-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_reviewerprofile_is_blocked_reviewerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerprofile',
            name='strikes',
            field=models.PositiveIntegerField(default=0, help_text='One strike per reported review. Auto-blocked at STRIKES_TO_BLOCK.'),
        ),
    ]
