# Generated by Django 5.2.16 on 2026-07-31 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_businessclaim_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessclaim',
            name='owner_token',
        ),
    ]
