# Generated by Django 5.2.17 on 2026-09-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_report_decided_at_report_decided_by_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(max_length=255),
        ),
    ]
