# Generated by Django 5.2.16 on 2026-07-31 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('new_area_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_requests', to='core.area')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_requests', to='core.category')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_requests', to='core.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_requests', to='core.region')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_requests', to=settings.AUTH_USER_MODEL)),
                ('resolved_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_request', to='core.listing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
